-- Full initialization script
-- 1) Create database (run as superuser, optional)
-- CREATE DATABASE vpn_new;

-- 2) Connect to the database (pgAdmin обычно уже подключён)
-- \c vpn_new

-- Sequences
CREATE SEQUENCE IF NOT EXISTS public.users_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.tariffs_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.peers_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.peer_logs_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.access_profiles_id_seq;

-- Tables
CREATE TABLE IF NOT EXISTS public.users
(
  id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  telegram_id bigint NOT NULL,
  username text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  vpn_status text DEFAULT 'active'::text,
  connections_count integer DEFAULT 0,
  tariff_id integer,
  tariff_expiry timestamp without time zone,
  referral_code text,
  referred_by_user_id integer,
  referred_at timestamp without time zone,
  referral_reward_granted_at timestamp without time zone,
  comment text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tariffs
(
  id integer NOT NULL DEFAULT nextval('tariffs_id_seq'::regclass),
  name text NOT NULL,
  duration_months integer NOT NULL,
  price numeric(10,2) NOT NULL,
  description text,
  duration_days integer DEFAULT 0,
  code text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  CONSTRAINT tariffs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id),
  tariff_id integer NOT NULL REFERENCES public.tariffs(id),
  amount numeric(10,2) NOT NULL,
  currency text NOT NULL DEFAULT 'RUB',
  status text NOT NULL DEFAULT 'pending',
  provider text NOT NULL DEFAULT 'manual',
  provider_ref text,
  details jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  paid_at timestamp without time zone,
  rejected_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.promo_codes
(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  description text,
  duration_days integer NOT NULL DEFAULT 30,
  max_redemptions integer NOT NULL DEFAULT 1,
  active boolean DEFAULT true,
  created_by_user_id integer REFERENCES public.users(id),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.promo_code_redemptions
(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promo_code_id integer NOT NULL REFERENCES public.promo_codes(id),
  user_id integer NOT NULL REFERENCES public.users(id),
  granted_days integer NOT NULL DEFAULT 0,
  redeemed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.servers
(
  id text NOT NULL,
  name text NOT NULL,
  ip text NOT NULL,
  host text,
  location text,
  role text DEFAULT 'edge'::text,
  country_code text,
  provider text,
  status text DEFAULT 'online'::text,
  enabled boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT servers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.routes
(
  id text NOT NULL,
  name text NOT NULL,
  entry_server_id text NOT NULL,
  exit_server_id text NOT NULL,
  protocol text DEFAULT 'managed-vpn'::text,
  profile_format text DEFAULT 'json'::text,
  enabled boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT routes_pkey PRIMARY KEY (id),
  CONSTRAINT routes_entry_server_id_fkey FOREIGN KEY (entry_server_id) REFERENCES public.servers(id),
  CONSTRAINT routes_exit_server_id_fkey FOREIGN KEY (exit_server_id) REFERENCES public.servers(id)
);

CREATE TABLE IF NOT EXISTS public.peers
(
  id integer NOT NULL DEFAULT nextval('peers_id_seq'::regclass),
  user_id integer,
  server_id text,
  route_id text,
  name text NOT NULL,
  public_key text,
  private_key text,
  ip text NOT NULL,
  protocol text DEFAULT 'managed-vpn'::text,
  access_uri text,
  config_payload jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  active boolean DEFAULT true,
  CONSTRAINT peers_pkey PRIMARY KEY (id),
  CONSTRAINT peers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT peers_server_id_fkey FOREIGN KEY (server_id) REFERENCES public.servers(id)
);

CREATE TABLE IF NOT EXISTS public.peer_logs
(
  id integer NOT NULL DEFAULT nextval('peer_logs_id_seq'::regclass),
  user_id integer,
  peer_name text,
  action text NOT NULL,
  details jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT peer_logs_pkey PRIMARY KEY (id),
  CONSTRAINT peer_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.access_profiles
(
  id integer NOT NULL DEFAULT nextval('access_profiles_id_seq'::regclass),
  user_id integer NOT NULL,
  route_id text NOT NULL,
  server_id text,
  profile_name text NOT NULL,
  profile_token text,
  protocol text DEFAULT 'managed-vpn'::text,
  profile_format text DEFAULT 'json'::text,
  access_uri text,
  config_payload jsonb DEFAULT '{}'::jsonb,
  provider_meta jsonb DEFAULT '{}'::jsonb,
  active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  revoked_at timestamp without time zone,
  CONSTRAINT access_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT access_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT access_profiles_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id),
  CONSTRAINT access_profiles_server_id_fkey FOREIGN KEY (server_id) REFERENCES public.servers(id)
);

-- FK users -> tariffs (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'users_tariff_id_fkey'
  ) THEN
    ALTER TABLE public.users
      ADD CONSTRAINT users_tariff_id_fkey FOREIGN KEY (tariff_id)
      REFERENCES public.tariffs(id);
  END IF;
END $$;

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS users_telegram_id_uq ON public.users (telegram_id);
CREATE UNIQUE INDEX IF NOT EXISTS users_referral_code_uq ON public.users (referral_code);
CREATE UNIQUE INDEX IF NOT EXISTS peers_name_uq ON public.peers (name);
CREATE INDEX IF NOT EXISTS peers_user_id_idx ON public.peers (user_id);
CREATE INDEX IF NOT EXISTS peers_server_id_idx ON public.peers (server_id);
CREATE INDEX IF NOT EXISTS users_referred_by_user_id_idx ON public.users (referred_by_user_id);
CREATE INDEX IF NOT EXISTS peer_logs_user_id_idx ON public.peer_logs (user_id);
CREATE INDEX IF NOT EXISTS access_profiles_user_id_idx ON public.access_profiles (user_id);
CREATE INDEX IF NOT EXISTS access_profiles_route_id_idx ON public.access_profiles (route_id);
CREATE INDEX IF NOT EXISTS access_profiles_server_id_idx ON public.access_profiles (server_id);
CREATE UNIQUE INDEX IF NOT EXISTS access_profiles_profile_name_uq ON public.access_profiles (profile_name);
CREATE UNIQUE INDEX IF NOT EXISTS servers_name_uq ON public.servers (name);
CREATE UNIQUE INDEX IF NOT EXISTS servers_ip_uq ON public.servers (ip);
CREATE UNIQUE INDEX IF NOT EXISTS tariffs_name_uq ON public.tariffs (name);
CREATE UNIQUE INDEX IF NOT EXISTS tariffs_code_uq ON public.tariffs (code);
CREATE UNIQUE INDEX IF NOT EXISTS routes_name_uq ON public.routes (name);
CREATE INDEX IF NOT EXISTS payments_user_id_idx ON public.payments (user_id);
CREATE INDEX IF NOT EXISTS payments_status_idx ON public.payments (status);
CREATE UNIQUE INDEX IF NOT EXISTS promo_codes_code_uq ON public.promo_codes (code);
CREATE UNIQUE INDEX IF NOT EXISTS promo_code_redemptions_promo_user_uq ON public.promo_code_redemptions (promo_code_id, user_id);
CREATE INDEX IF NOT EXISTS promo_code_redemptions_promo_code_id_idx ON public.promo_code_redemptions (promo_code_id);

-- Seed data
INSERT INTO public.servers (id, name, ip, host, location, role, country_code, is_default)
VALUES
  ('ru-entry-main', 'RU Entry Main', '203.0.113.1', 'entry.example.com', 'Russia', 'entry', 'RU', true),
  ('foreign-exit-main', 'Foreign Exit Main', '176.98.191.110', 'vpnnew1.com', 'Singapore', 'exit', 'SG', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.routes (id, name, entry_server_id, exit_server_id, protocol, profile_format, enabled, is_default)
VALUES ('ru-foreign-default', 'RU Entry -> Foreign Exit', 'ru-entry-main', 'foreign-exit-main', 'managed-vpn', 'json', true, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tariffs (code, name, duration_months, price, description, duration_days, is_active, sort_order)
VALUES
  ('trial-30d', 'Пробный период', 1, 0.00, 'Первый месяц бесплатно', 30, true, 0),
  ('plan-1m', '1 месяц', 1, 190.00, 'Подписка на 1 месяц', 30, true, 10),
  ('plan-3m', '3 месяца', 3, 490.00, 'Подписка на 3 месяца', 90, true, 20),
  ('plan-6m', '6 месяцев', 6, 990.00, 'Подписка на 6 месяцев', 180, true, 30),
  ('plan-lifetime', 'Навсегда', 1200, 9000.00, 'Пожизненный доступ без продления', 36500, true, 40),
  ('service-personal-vpn', 'Личный VPN сервер', 0, 15000.00, 'Разработка и настройка отдельного личного VPN сервера', 0, true, 50),
  ('promo-access', 'Промокод', 0, 0.00, 'Доступ, активированный через промокод', 0, true, 90),
  ('tester', 'tester', 0, 0.00, 'Тестовый тариф', 0, true, 100)
ON CONFLICT (code) DO NOTHING;
